# Generated by Django 5.1.3 on 2024-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kitob_yili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='yili',
            field=models.DateField(),
        ),
    ]
